FROM openjdk:23-jdk-oraclelinux9 AS builder

RUN groupadd -g 1234 springGroup && useradd -m -u 1234 -g springGroup springUser
USER springUser:springGroup

WORKDIR /chat-app-api

ARG JAR_FILE=target/chat-app-0.0.1-SNAPSHOT.jar
ARG LOCAL_URL=http://localhost:8080

COPY ${JAR_FILE} app.jar

HEALTHCHECK --interval=5s \
            --timeout=3s \
            CMD curl -f ${LOCAL_URL}/health || exit 1

RUN chown springUser:springGroup .

ENTRYPOINT ["java","-jar","/chat-app-api/app.jar"]
