name: chat-app
include:
   - ../chat-app-front/docker-compose-dev.yml
services:
  backend:
    image: chat-app-back-dev-image
    container_name: chat-app-back-dev-container
    build:
      context: .
      dockerfile: Dockerfile-dev
    restart: unless-stopped
    volumes:
      - chat-app-api:/chat-app-api/src
    ports:
      - 8080:8080
    networks:
      - chat-app
    user: springUser
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /chat-app-api/src
          ignore:
            - ./target
    command: /chat-app-api/mvnw spring-boot:run
volumes:
  chat-app-api:
networks:
  chat-app:
    driver: bridge
